# Información del proyecto
sonar.projectKey=aeroflash-project
sonar.projectName=AeroFlash-Project
sonar.projectVersion=1.0

# Directorio raíz del proyecto
sonar.sources=.

# Codificación
sonar.sourceEncoding=UTF-8

# Exclusiones
sonar.exclusions=**/.terraform/**,\
**/*.tfstate,\
**/venv/**,\
**/__pycache__/**,\
**/node_modules/**,\
**/dist/**,\
**/.git/**,\
**/*.min.js

# Inclusión de archivos Python
sonar.python.file.suffixes=.py

# Inclusión de archivos TypeScript (Angular)
sonar.typescript.file.suffixes=.ts

# Inclusión de archivos Terraform
sonar.terraform.file.suffixes=.tf
